{% set version = "2.1.1" %}
{% set cov_fail_under = 86 %}
{% set test_skip = "\"-k not exclude_patterns\"" %}

package:
  name: werkzeug
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/W/Werkzeug/Werkzeug-{{ version }}.tar.gz
  sha256: f8e89a20aeabbe8a893c24a461d3ee5dad2123b05cc6abd73ceed01d39c3ae74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  source_files:
    - tests
  requires:
    - cryptography
    - ephemeral-port-reserve
    - greenlet
    - pip
    - pytest
    - pytest-cov
    - pytest-timeout
    - pytest-xprocess
    - watchdog
  imports:
    - werkzeug
  commands:
    - pip check
    - pytest tests -vv --cov=werkzeug --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under={{ cov_fail_under }} {{ test_skip }}

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
    - bollwyvl
