{% set version = "2.0.2" %}
{% set cov_fail_under = 82 %}

package:
  name: werkzeug
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/W/Werkzeug/Werkzeug-{{ version }}.tar.gz
  sha256: aa2bb6fc8dee8d6c504c0ac1e7f5f7dc5810a9903e793b6f715a9f015bdadb9a

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses

test:
  source_files:
    - tests
  requires:
    - cryptography
    - greenlet
    - pip
    - pytest
    - pytest-timeout
    - pytest-xprocess
    - watchdog
    - pytest-cov
  imports:
    - werkzeug
  commands:
    - pip check
    - pytest tests -vv --cov werkzeug --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under {{ cov_fail_under }}

about:
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: The comprehensive WSGI web application library.
  description: |
    Werkzeug is a WSGI utility library for Python. It's widely used and BSD licensed.
  doc_url: https://werkzeug.palletsprojects.com/
  dev_url: https://github.com/pallets/werkzeug

extra:
  recipe-maintainers:
    - goanpeca
    - mcs07
    - bollwyvl
